language: python

sudo: required
dist: trusty

python:
#   - "2.6"
   - "2.7"
#   - "3.2"
#   - "3.3"
#   - "3.4"
install:
   - sudo apt-get install -y geoip-database python-geoip
   - pip install pycrypto SQLAlchemy twisted pyOpenSSL

script:
   - python3 protocol/Protocol.py
   - python3 ip2country.py
   - ./SQLUsers.py
   - ./server.py &
   - sleep 30 # wait for server to start up
   - python3 tests/TestLobbyClient.py
   - sleep 10 # give server some time to write log, etc
   - killall python
